print("======"  "DESAFIO 73" "======")
t = ("Athletico-PR", "Atlético-GO", "Atlético-MG", "Bahia", "Botafogo", "Corinthians", "Criciúma", "Cruzeiro", "Cuiabá", "Flamengo", "Fluminense", "Fortaleza", "Grêmio", "Internacional", "Juventude", "Palmeiras", "Bragrantino", "São Paulo", "Vasco da Gama", "EC Vitória")
print("=" * 30)
print("Lista do brasileirão 2024: {}".format(t))
print("=" * 30)
print("O 5 primeiros colocados são {}.".format(t[0:5]))
print("=" * 30)
print("Os ultimos 4 colocados são {}.".format(t[-4:]))
print("=" * 30)
print("Em ordem alfabética são {}.".format(sorted(t)))
print("=" * 30)
print("A chapecoense não se encontra na lista do brasileirão 2024.")
print("=" * 30)