import random
print("======"  "DESAFIO 74" "======")
n1 = random.randint(0,10)
n2 = random.randint(0,10)
n3 = random.randint(0,10)
n4 = random.randint(0,10)
n5 = random.randint(0,10)
n = (n1, n2, n3, n4, n5)
print("O valores sorteados foram: {} {} {} {} {}".format(n1, n2, n3, n4, n5))
print("O maior valor sorteado foi {}".format(max(n)))
print("O menor valor sorteado foi {}".format(min(n)))